export const style = {
  section: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.25rem",
    paddingBottom: "3rem",
  },
  heading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
  },
  title: {
    letterSpacing: "0.56px",
    lineHeight: "54px",
  },
  subtitle: {
    letterSpacing: "0.29px",
    lineHeight: "27px",
    color: "#5b6672",
    textAlign: "center",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "minmax(0, 1fr)",
      sm: "repeat(2, minmax(0, 1fr))",
      lg: "repeat(3, minmax(0, 1fr))",
    },
    gap: { xs: "1.25rem", md: "1.75rem" },
    width: "100%",
    maxWidth: "1180px",
    margin: "1.5rem auto 0",
    alignItems: "stretch",
  },

  card: {
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    borderRadius: "25px",
    backgroundColor: "#ffffff",
    border: "1px solid #f1f5f9",
    boxShadow:
      "0 1.5px 3px rgba(0, 0, 0, 0.02), 0 4px 8px rgba(0, 0, 0, 0.03), 0 10px 18px rgba(0, 0, 0, 0.04)",
    transition: "all 0.3s ease",
    cursor: "pointer",
    "&:hover": {
      transform: "translateY(-8px)",
      borderColor: "#cbd5e1",
      boxShadow:
        "0 3px 6px rgba(0, 0, 0, 0.03), 0 8px 16px rgba(0, 0, 0, 0.04), 0 18px 30px rgba(0, 0, 0, 0.06), 0 32px 50px rgba(0, 0, 0, 0.07)",
    },
  },
  accentBar: {
    height: "6px",
    flexShrink: 0,
    background:
      "linear-gradient(to right, #CEA0D0 0%, #968DD4 35%, #7D9AE2 65%, #8DC3F2 100%)",
  },
  content: {
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    padding: { xs: "1.5rem 1.5rem 0.75rem", md: "1.75rem 1.75rem 0.75rem" },
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    marginBottom: "0.75rem",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    width: "fit-content",
    padding: "5px 14px",
    borderRadius: "999px",
    backgroundColor: "#EEF2FF",
    color: "#6C8EA5",
    fontSize: "0.8125rem",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    marginBottom: "0.5rem",
  },
  cardTitle: {
    fontWeight: 700,
    color: "#0f172a",
    lineHeight: 1.35,
    minHeight: "calc(2 * 1.35em)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    overflowWrap: "anywhere",
  },
  description: {
    color: "#475569",
    lineHeight: 1.7,
    overflowWrap: "anywhere",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  descriptionFade: {
    WebkitMaskImage: "linear-gradient(to bottom, black 78%, transparent 98%)",
    maskImage: "linear-gradient(to bottom, black 78%, transparent 98%)",
  },
  readMore: {
    display: "inline-flex",
    alignItems: "center",
    gap: "2px",
    marginTop: "0.5rem",
    width: "fit-content",
    color: "#6C8EA5",
    fontWeight: 600,
    fontSize: "0.9rem",
    cursor: "pointer",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  actions: {
    display: "flex",
    justifyContent: "center",
    padding: "0.75rem 1.25rem 1.25rem",
    backgroundColor: "#fafbff",
    borderTop: "1px solid #eef2ff",
  },
};
