export const style = {
  pricingSection: {
    padding: { xs: "70px 0", md: "110px 0" },
    background:
      "linear-gradient(180deg, #fcfcfc 0%, #f5f8fb 100%)",
    borderTop: "1px solid #f0f0f0",
  },
  header: {
    textAlign: "center",
    mb: { xs: 5, md: 7 },
  },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 16px",
    borderRadius: "999px",
    backgroundColor: "#eef4f7",
    color: "#6C8EA5",
    fontSize: "0.8rem",
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    mb: 2,
  },
  title: {
    fontSize: { xs: "2rem", md: "3rem" },
    fontWeight: 800,
    lineHeight: 1.15,
    color: "#0f172a",
    mb: 2,
  },
  subtitle: {
    fontSize: { xs: "1rem", md: "1.15rem" },
    color: "#5b6672",
    maxWidth: "620px",
    margin: "0 auto",
    lineHeight: 1.7,
  },
  billingToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 1.5,
    mt: 4,
  },
  billingLabel: {
    fontSize: "0.95rem",
    fontWeight: 600,
    color: "#94a3b8",
    transition: "color 0.2s ease",
    cursor: "pointer",
  },
  billingLabelActive: {
    color: "#0f172a",
  },
  saveBadge: {
    marginLeft: "8px",
    fontSize: "0.7rem",
    fontWeight: 700,
    color: "#6C8EA5",
    backgroundColor: "#eef4f7",
    borderRadius: "999px",
    padding: "3px 8px",
  },
  toggleTrack: {
    width: "54px",
    height: "30px",
    borderRadius: "999px",
    backgroundColor: "#d8e2ea",
    position: "relative",
    cursor: "pointer",
    transition: "background-color 0.25s ease",
  },
  toggleTrackActive: {
    backgroundColor: "#6C8EA5",
  },
  toggleThumb: {
    position: "absolute",
    top: "3px",
    left: "3px",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#ffffff",
    boxShadow: "0 2px 6px rgba(15,23,42,0.25)",
    transition: "transform 0.25s ease",
  },
  toggleThumbActive: {
    transform: "translateX(24px)",
  },
  grid: {
    display: "flex",
    flexWrap: "wrap",
    gap: { xs: 3, md: 4 },
    justifyContent: "center",
    alignItems: "stretch",
    mt: 5,
  },
  card: {
    flex: { xs: "1 1 100%", sm: "1 1 320px", md: "0 1 340px" },
    maxWidth: { xs: "420px", md: "360px" },
    backgroundColor: "#ffffff",
    borderRadius: "24px",
    border: "1px solid #eef2f6",
    padding: { xs: "32px 26px", md: "38px 32px" },
    display: "flex",
    flexDirection: "column",
    position: "relative",
    boxShadow:
      "0 1.5px 3px rgba(0,0,0,0.02), 0 4px 8px rgba(0,0,0,0.03), 0 10px 18px rgba(0,0,0,0.04)",
    transition: "all 0.3s ease",
    "&:hover": {
      transform: "translateY(-8px)",
      boxShadow:
        "0 3px 6px rgba(0,0,0,0.03), 0 8px 16px rgba(0,0,0,0.04), 0 18px 30px rgba(0,0,0,0.06), 0 32px 50px rgba(0,0,0,0.07)",
      borderColor: "#cbd5e1",
    },
  },
  popularCard: {
    border: "1.5px solid transparent",
    backgroundImage:
      "linear-gradient(#ffffff, #ffffff), linear-gradient(135deg, #CEA0D0 0%, #968DD4 45%, #7D9AE2 75%, #8DC3F2 100%)",
    backgroundOrigin: "border-box",
    backgroundClip: "padding-box, border-box",
    boxShadow: "0px 24px 60px rgba(108,142,165,0.18)",
  },
  popularBadge: {
    position: "absolute",
    top: "-14px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "#968DD4",
    color: "#ffffff",
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    padding: "6px 16px",
    borderRadius: "999px",
    boxShadow: "0 6px 16px rgba(150,141,212,0.4)",
  },
  planName: {
    fontSize: "1.35rem",
    fontWeight: 800,
    color: "#0f172a",
    mb: 0.5,
  },
  planTagline: {
    fontSize: "0.9rem",
    color: "#64748b",
    lineHeight: 1.5,
    minHeight: { md: "42px" },
    mb: 2,
  },
  priceRow: {
    display: "flex",
    alignItems: "baseline",
    gap: "4px",
    mb: 0.5,
  },
  price: {
    fontSize: "2.6rem",
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1,
  },
  pricePeriod: {
    fontSize: "0.95rem",
    color: "#94a3b8",
    fontWeight: 600,
  },
  priceNote: {
    fontSize: "0.82rem",
    color: "#94a3b8",
    mb: 3,
  },
  divider: {
    height: "1px",
    backgroundColor: "#eef2f6",
    width: "100%",
    mb: 3,
  },
  featureList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: 1.6,
    flexGrow: 1,
  },
  featureItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 1.2,
    fontSize: "0.95rem",
    color: "#475569",
    lineHeight: 1.5,
  },
  featureIcon: {
    color: "#6C8EA5",
    fontSize: "1.25rem",
    flexShrink: 0,
    mt: "1px",
  },
  ctaButton: {
    minWidth: "100%",
    borderRadius: "999px",
    textTransform: "none",
    marginTop: 3.5,
  },
};
